# Generated by Django 5.1 on 2025-08-20 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(blank=True, max_length=60, null=True)),
                ("name", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=30, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_user_id", models.CharField(max_length=50)),
                ("state_node", models.CharField(default="START", max_length=60)),
                ("is_active", models.BooleanField(default=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=60, unique=True)),
                ("text", models.TextField()),
                ("locale", models.CharField(default="pt-BR", max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="ProviderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("payments", "Payments"),
                            ("xps247", "XPS247"),
                            ("fx", "FX"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("base_url", models.URLField(blank=True, null=True)),
                ("api_key", models.CharField(blank=True, max_length=255, null=True)),
                ("secret", models.CharField(blank=True, max_length=255, null=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=20)),
                ("payload", models.JSONField()),
                ("status", models.CharField(default="ok", max_length=30)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MessageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "in"), ("out", "out")], max_length=3
                    ),
                ),
                ("payload", models.JSONField()),
                ("status", models.CharField(default="ok", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.conversation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "beneficiary_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "beneficiary_cpf",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("pix_key", models.CharField(blank=True, default="", max_length=120)),
                ("address", models.TextField(blank=True, default="")),
                (
                    "amount_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "rate_used",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                (
                    "fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "amount_brl_estimated",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("awaiting_payment", "awaiting_payment"),
                            ("paid", "paid"),
                            ("failed", "failed"),
                            ("cancelled", "cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("payment_link", models.URLField(blank=True, null=True)),
                (
                    "payment_provider_ref",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.client"
                    ),
                ),
            ],
        ),
    ]
