# Generated by Django 5.1 on 2025-08-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="is_registered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="client",
            name="password_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="registration_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="client",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="client",
            name="username",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="context_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="conversation",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
